CREATE DATABASE SPRING_MVC_TRAINING;

USE SPRING_MVC_TRAINING;

CREATE TABLE MEMBER (
    MEMBER_ID 		VARCHAR(20) PRIMARY KEY,
    PASSWD 			VARCHAR(200) NOT NULL,
    PROFILE			VARCHAR(200) NOT NULL,
	MEMBER_NM 		VARCHAR(50)  NOT NULL,
	SEX 			CHAR(1)  	 NOT NULL,
	BIRTH_DT 		CHAR(10)     NOT NULL, 
	HP 				VARCHAR(13)  NOT NULL,
	SMSSTS_YN 		CHAR(1)   	 NOT NULL,
	EMAIL 			VARCHAR(30)  NOT NULL,
	EMAILSTS_YN 	CHAR(1)   	 NOT NULL,
	ZIPCODE 		VARCHAR(10),
	ROAD_ADDRESS 	VARCHAR(200),
	JIBUN_ADDRESS 	VARCHAR(200),
	NAMUJI_ADDRESS 	VARCHAR(200),
	JOIN_DT 		TIMESTAMP,
	ETC 			VARCHAR(3000)
);

